# Generated by Django 4.2.3 on 2023-07-17 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenregister',
            old_name='user',
            new_name='email',
        ),
    ]
