# Generated by Django 4.2.3 on 2023-07-18 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_rename_user_tokenregister_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenResetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokenresetpassword', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
