# Generated by Django 4.2.3 on 2023-07-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('selling_price', models.FloatField(blank=True, default='', null=True)),
                ('discounted_price', models.FloatField(default='')),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('Điện thoại', 'Điện thoại'), ('Laptop', 'Laptop'), ('Tablet', 'Tablet'), ('Phụ kiện', 'Phụ kiện')], max_length=20, null=True)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
