# Generated by Django 4.2.3 on 2023-07-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
